-- EMERGENCY RECOVERY SCRIPT
-- RUN THIS IN RAILWAY CONSOLE IF EVERYTHING FAILS
DROP TABLE IF EXISTS "session" CASCADE;
DROP TABLE IF EXISTS comment_reactions CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS user_topics CASCADE;
DROP TABLE IF EXISTS user_favorite_topics CASCADE;
DROP TABLE IF EXISTS user_favorites CASCADE;
DROP TABLE IF EXISTS page_revisions CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS pages CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS wikis CASCADE;

CREATE TABLE wikis (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO wikis (name, slug, description)
VALUES ('Wiki General', 'general', 'Espacio principal de la wiki');
